# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: 'log'
author: Author Name
domain: http://blog.author/

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: 'main'

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: 'UTF-8'

# You can use any template you wish. 
# Please see 
# http://search.cpan.org/search?query=Dancer%3A%3ATemplate&mode=all
# for current template options.
#
# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: 'haml'
engines:
  haml:
    extension: 'haml'
#
# template: 
# engines:
#   template_toolkit:
#     encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'


# This blog engine uses SQLite. 
# However, the queries found in lib/
# lib/log are compatible with other DBs.
#
# Setttings for Dancer::Plugin::Database 
plugins:
    Database:
            driver: 'SQLite'
            database: 'lib/database.db'

# Settings for Dancer::Plugin::Feed
    Feed:
        title: Author blog
        copyright: Author Name
        link: http://blog.author/
        tagline: blog.author, a blog by author.
        description: blog.author - A blog by author.


